server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopease_db
    username: ecom_user
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev